import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar/Navbar";
import Footer from "@/component/footer/Footer";
import clientSideProvider from "@/component/clientSideProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <clientSideProvider> */}
        <div className="container">
          <Navbar/>
        {children}
        <Footer/>
        </div>
        {/* </clientSideProvider> */}
        </body>
      
    </html>
  );
}
